sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - bower_components
branches:
  only:
      - master
notifications:
  email: false
node_js:
  - 4.1
before_install:
  - npm install -g gulp
before_script:
  - npm prune
script:
  - npm run test
